global:
  scrape_interval:     "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fridge_temperature"
    scrape_interval: "1s"
    static_configs:
    - targets: ["localhost:8000"]
      labels:
        fridge_id: 00001
  
