# my global config
global:
  scrape_interval:     1s
  evaluation_interval: 10s

# rule_files:
# - "temperature.rules"

scrape_configs:
- job_name: "prometheus"
  static_configs:
    - targets: ["localhost:9090"]
        

- job_name: "request_processing_seconds"
  static_configs:
    - targets: ["localhost:8000"]

- job_name: "fridge_temperature"
  static_configs:
  - targets: ["localhost:8000"]
    labels:
      fridge_id: 00001
  
# alerting:
#   alertmanagers:
#   - scheme: https
#     static_configs:
#     - targets:
#       - "1.2.3.4:9093"
#       - "1.2.3.5:9093"
#       - "1.2.3.6:9093"